app/urls.py
from app import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('studentManagement', views.studentManagement, name='studentManagement'),
    path('register/', views.register, name='register'),
    path('profile', views.profile, name='profile'),
    path('logout', views.logoutView, name='logout'),
    path('content/', views.postContent, name='content'),
    path('student-logs/<int:id>/', views.studentInformation, name='student-logs'),
    # 
    path('changePass', views.changePass, name='changePass'),
    path('dashboard', views.mainDashboard, name='dashboard'),
    path('student-list', views.getAllListStudent, name='student-list'),
    path('student-submitted-list', views.getAllStudentSubmittedRequirements, name='student-submitted-list'),
    path('approve-student-list', views.getAllApproveStudents, name='approve-student-list'),
    path('pending-student-list', views.getAllPendingStudents, name='pending-student-list'),
    path('reject-student-list', views.getAllRejectStudents, name='reject-student-list'),
    path('computer-science-list', views.computerScienceStudents, name='computer-science-list'),
    path('information-technology-list', views.informationTechnologyStudents, name='information-technology-list'),
    path('editStudentDetails/<int:id>/', views.editStudentDetails, name='editStudentDetails'),
    # 
    path('approve_student/<int:id>/', views.approveStudent, name='approve_student'),
    path('reject_students/<int:id>/', views.rejectStudent, name='reject_students'),
    # 
    path('archivedStudent/<int:id>/', views.archivedStudent, name='archivedStudent'),
    path('get_admin_password_hash/', views.getAdminPasswordHash, name='get_admin_password_hash'),
    path('validate_admin_password/', views.validateAdminPassword, name='validate_admin_password'),
    
    path('unArchivedStudent/<int:id>/', views.unArchivedStudent, name='unArchivedStudent'),
    # 
    path('viewPendingApplication/<int:id>/', views.viewPendingApplication, name='viewPendingApplication'),
    path('view-student-details/<int:id>/', views.showStudentDetails, name='view-student-details'),
    path('setSchedule/<int:id>/', views.setSchedule, name='setSchedule'),
    # 
    path('announcement', views.postAnnouncement, name='announcement'),
    path('listOfAnnouncement', views.listOfAnnouncement, name='listOfAnnouncement'),
    path('all-content', views.listOfContent, name='all-content'),
    path('grading', views.getAllStudentsForGrading, name='grading'),
    path('submission', views.getTheSubmitRequirements, name='submission'),
    path('editAnnouncement/<int:id>/', views.editAnnouncement, name='editAnnouncement'),
    path('editContent/<int:id>/', views.editContent, name='editContent'),
    path('deleteAnnouncement/<int:id>/', views.deleteAnnouncement, name='deleteAnnouncement'),
    path('deleteContent/<int:id>/', views.deleteContent, name='deleteContent'),
    path('deleteRequirementDocuments/<int:id>/', views.deleteRequirementDocuments, name='deleteRequirementDocuments'),
    path('gradeCalculator/<int:id>/', views.gradeCalculator, name='gradeCalculator'),
    #
    path('set_rendering_hours/', views.set_rendering_hours, name='set_rendering_hours'),
    path('announcementNotLogin/', views.getAnnouncementNotLogin, name='announcementNotLogin'),
    path('announcementLogin/', views.getAnnouncement, name='announcementLogin'),
    path('return_to_revision/<int:id>/', views.return_to_revision, name='return_to_revision'),
    path('approve_document/<int:id>/', views.approve_document, name='approve_document'),
    path('update_document_score/<int:id>/', views.update_document_score, name='update_document_score'),
    path('view-requirements/<int:id>/', views.submittedRequirementOfStudents, name='view-requirements'),
    path('view-document/<int:id>/', views.submittedRequirementsOfStudents, name='view-document'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('students.urls')),
    path('admin/', admin.site.urls),
    path('coordinator/', include('app.urls')),
    path('secret-page/', include('superapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

students/urls.py
from students import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'students'

urlpatterns = [
    # path('', views.studentHome, name='home'),
    path('about/', views.aboutPage, name='about'),
    # path('login', views.studentLogin, name='login'),
    path('logout/', views.studentLogout, name='logout'),
    path('profile/', views.studentProfile, name='profile'),
    path('clockin/', views.ClockInAndOut, name='clockin'),
    path('about-page/', views.aboutLogin, name='about-page'),
    path('register/', views.studentRegister, name='register'),
    path('schedule/', views.scheduleSettings, name='schedule'),
    path('download/', views.exportTimeLogToPDF, name='download'),
    path('main-page/', views.welcomeDashboard, name='main-page'),
    path('requirements/', views.getTheRequirement, name='requirements'),
    path('delete_submission/<int:id>/', views.delete_submission, name='delete_submission'),
    path('log_lunch/', views.log_lunch, name='log_lunch'),
    path('dashboard/', views.mainPageForDashboard, name='dashboard'),
    path('announcement/', views.getAnnouncement, name='announcement'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/<str:token>/', views.reset_password, name='reset_password'),
    path('list-of-document/', views.getAllSubmittedDocuments, name='list-of-document'),
    path('announcement-page/', views.getAnnouncementNotLogin, name='announcement-page'),
    path('progress-report', views.typeTheDetailsProgressReportPdf, name='progress-report'),
    path('mark-notification-as-read/<int:id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

students/views.py
import os
import fitz
from io import BytesIO
from django.urls import reverse
from django.conf import settings
from django.utils import timezone
from django.contrib import messages
from django.core.mail import send_mail
from datetime import datetime, timedelta
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.utils.crypto import get_random_string
from django.template.loader import render_to_string
from django.views.decorators.cache import never_cache
from django.views.decorators.cache import cache_control
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.contrib.auth.hashers import check_password, make_password
from app.models import TableAnnouncement, TableRequirements, TableContent
from students.models import DataTableStudents, TimeLog, Schedule, TableSubmittedReport, TableSubmittedRequirement, PendingApplication, ApprovedDocument, ReturnToRevisionDocument, LunchLog, Notification
from students.forms import ChangePasswordForm, StudentProfileForm, ScheduleSettingForm, ProgressReportForm, SubmittedRequirement, PendingStudentRegistrationForm, TimeLogForm, ResetPasswordForm, LunchLogForm

@never_cache
@login_required
@csrf_exempt
def studentHome(request) -> HttpResponse:
    images = TableContent.objects.all().order_by('id')
    return render(
        request, 'students/student-base.html',
        {
            'images': images
        }
    )

@never_cache
@csrf_protect
@login_required
def studentDashboard(request) -> HttpResponse:
    images = TableContent.objects.all().order_by('id')
    return render(
        request, 'students/student-dashboard.html',
        {
            'images': images
        }
    )

@login_required
@never_cache
@csrf_protect
@cache_control(no_cache=True, must_revalidate=True, no_store=True, name='dispatch')
def welcomeDashboard(request) -> HttpResponse:
    # Check if the user is NOT a staff or a superuser
    if request.user.is_staff or request.user.is_superuser:
        return render(request, 'main/404.html', status=403)  
    # Proceed if the user is a student
    user = request.user
    student = get_object_or_404(DataTableStudents, user=user)
    firstName = student.Firstname
    lastName = student.Lastname
    images = TableContent.objects.all().order_by('id')
    notifications = Notification.objects.filter(student=student, is_read=False)
    unread_notifications_count = notifications.count()

    return render(
        request,
        'students/student-main-dashboard.html',
        {
            'firstName': firstName,
            'lastName': lastName,
            'notifications': notifications,
            'unread_notifications_count': unread_notifications_count,
            'images': images
        }
    )

@never_cache
@login_required
@csrf_exempt
def getAnnouncement(request):
    enabledAnnouncement = TableAnnouncement.objects.filter(Status='enable')
    return render(
        request, 'students/announcement.html', 
        {
            'announcements': enabledAnnouncement
        }
    )

@never_cache
@login_required
@csrf_exempt
def getAnnouncementNotLogin(request):
    enabledAnnouncement = TableAnnouncement.objects.filter(Status='enable')
    return render(
        request, 'students/announcementNotLogin.html', 
        {
            'announcements': enabledAnnouncement
        }
    )

@never_cache
@login_required
@csrf_exempt
def aboutPage(request):
    contents = TableContent.objects.all().order_by('id')
    return render(
        request, 'students/about.html',
        {
            'contents': contents
        }
    )

@never_cache
@login_required
@csrf_exempt
def aboutLogin(request):
    contents = TableContent.objects.all().order_by('id')
    return render(
        request, 'students/aboutLogin.html',
        {
            'contents': contents
        }
    )

@never_cache
@login_required
@csrf_exempt
def mainPageForDashboard(request) -> HttpResponse:
    user = request.user
    student = get_object_or_404(DataTableStudents, user=user)
    # 
    studentID = student.StudentID
    firstName = student.Firstname
    lastName = student.Lastname
    email = student.Email
    course = student.Course
    year = student.Year
    # 
    notifications = Notification.objects.filter(student=student, is_read=False)
    unread_notifications_count = notifications.count()
    return render(
        request,
        'students/student-dashboard.html',
        {
            'firstName': firstName,
            'lastName': lastName,
            'email': email,
            'course': course,
            'year': year,
            'student': student,
            'studentID': studentID,
            'notifications': notifications,
            'unread_notifications_count': unread_notifications_count,
        }
    )

def mark_notification_as_read(request, id):
    if request.method == 'POST':
        notification = get_object_or_404(Notification, id=id)
        notification.is_read = True
        notification.save()
        return redirect('students:dashboard')
    return None

def draw_wrapped_text(page, text, start_pos, max_width, fontsize=12, fontname="helv"):
    """
    Draws wrapped text within the specified width on a given PDF page.

    :param page: The PyMuPDF page object.
    :param text: The text to be drawn.
    :param start_pos: Starting position (x, y) tuple for the text.
    :param max_width: Maximum width allowed for each line.
    :param fontsize: Font size for the text.
    :param fontname: Font name to be used.
    """
    x, y = start_pos
    rect = fitz.Rect(x, y, x + max_width, y + 1000)
    page.insert_textbox(rect, text, fontsize=fontsize, fontname=fontname, align=0)

def typeTheDetailsProgressReportPdf(request):
    user = request.user
    student = get_object_or_404(DataTableStudents, user=user)
    firstName = student.Firstname or ''
    middleName = student.Middlename or ''
    lastName = student.Lastname or ''
    notifications = Notification.objects.filter(student=student, is_read=False)
    unread_notifications_count = notifications.count()
    full_name = f"{firstName} {middleName} {lastName}".strip()
    # Calculate total work hours for each day in the current week
    current_date = timezone.now().date()
    week_start = current_date - timedelta(days=current_date.weekday())
    week_end = week_start + timedelta(days=6)
    work_hours_per_day = {
        'monday': 0,
        'tuesday': 0,
        'wednesday': 0,
        'thursday': 0,
        'friday': 0,
    }
    # Retrieve time logs for the current week for the student
    time_logs = TimeLog.objects.filter(student=student, timestamp__date__range=[week_start, week_end]).order_by('timestamp')
    # Calculate work hours per day from the time logs
    for i in range(0, len(time_logs) - 1, 2):
        day = time_logs[i].timestamp.weekday()
        if i + 1 < len(time_logs) and time_logs[i + 1].timestamp > time_logs[i].timestamp:
            work_duration = (time_logs[i + 1].timestamp - time_logs[i].timestamp).total_seconds() / 3600
            if day == 0:  # Monday
                work_hours_per_day['monday'] += work_duration
            elif day == 1:  # Tuesday
                work_hours_per_day['tuesday'] += work_duration
            elif day == 2:  # Wednesday
                work_hours_per_day['wednesday'] += work_duration
            elif day == 3:  # Thursday
                work_hours_per_day['thursday'] += work_duration
            elif day == 4:  # Friday
                work_hours_per_day['friday'] += work_duration
    if request.method == 'POST':
        form = ProgressReportForm(request.POST)
        if form.is_valid():
            pdf_path = os.path.join(settings.PDF_ROOT, 'PROGRESS-REPORT.pdf')
            pdf_document = fitz.open(pdf_path)
            page = pdf_document[0]
            coordinates = {
                'name_field': (170, 157),
                'intern_name': (145, 707),
                'classification_local': (203, 185),
                'classification_international': (335, 185),
                'classification_in_campus': (225, 200),
                'classification_off_campus': (226, 215),
                'modality_actual': (204, 230),
                'modality_virtual': (335, 229),
                'virtual_wfh': (355, 245),
                'virtual_alternative': (355, 260),
                'hte_name': (170, 260),
                'hte_address': (170, 275),
                'department_division': (250, 290),
                'total_hours': (506, 652)
            }
            # Insert the student details and other values into the PDF
            page.insert_text(coordinates['name_field'], form.cleaned_data['student_name'], fontsize=12, color=(0, 0, 0))
            # Draw Internship Classification
            if form.cleaned_data['internship_classification'] == 'local':
                page.insert_text(coordinates['classification_local'], '✓', fontsize=45, color=(0, 0, 0))
            elif form.cleaned_data['internship_classification'] == 'international':
                page.insert_text(coordinates['classification_international'], '✓', fontsize=45, color=(0, 0, 0))
            # Draw Local Condition
            if form.cleaned_data['local_condition'] == 'inCampus':
                page.insert_text(coordinates['classification_in_campus'], '✓', fontsize=45, color=(0, 0, 0))
            elif form.cleaned_data['local_condition'] == 'offCampus':
                page.insert_text(coordinates['classification_off_campus'], '✓', fontsize=45, color=(0, 0, 0))
            # Draw Modality
            if form.cleaned_data['internship_modality'] == 'actual':
                page.insert_text(coordinates['modality_actual'], '✓', fontsize=45, color=(0, 0, 0))

students/templates/students/changePassword.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main-dashboard.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <title>Student - OJT Management System Dashboard</title>
    <style>
        .preview-box {
            border: 2px dashed #ccc;
            border-radius: 6px;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 260px;
            width: 255px;
            margin-bottom: 20px;
            position: relative;
            cursor: pointer;
            overflow: hidden;
            background-color: #f8f9fa;
        }
        .preview-box img {
            max-width: 100%;
            max-height: 100%;
        }
        .preview-box::before {
            content: 'Browse Image';
            color: #888;
            font-size: 16px;
            position: absolute;
            display: flex;
            align-items: center;
            justify-content: center;
            width: 100%;
            height: 100%;
        }
        .preview-box.with-image::before {
            display: none;
        }
        input[type='file'] {
            left: 12px;
            padding: 10px;
            height: 50px;
            margin-top: -10px;
        }
        .dropdown-menu {
            width: 350px;  /* Set a max width for the dropdown */
            word-wrap: break-word;  /* Allow long words to break */
            white-space: normal;  /* Ensure text can break into multiple lines */
        }

        .dropdown-item {
            white-space: normal;
            overflow-wrap: break-word;
            display: block;
            padding: 10px;
        }
    </style>
</head>

<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-light border-right vh-100" id="sidebar-wrapper">
            <a href="{% url 'students:main-page' %}" style="text-decoration: none !important; color: black !important;" class="text-center">
                <div class="sidebar-heading" style="display: flex; align-items: center; justify-content: flex-start;">
                    <img src="{% static 'img/Logo.png' %}" alt="Logo" style="width: 50px; height: 50px; margin-right: 2px;">
                    <div style="display: flex; flex-direction: column; line-height: 1; margin-top: 2px;">
                        <span style="font-size: 18px; font-weight: 500; margin-bottom: 0;" class="text-left mb-1">On the Job</span>
                        <span style="font-size: 15px;">Management System</span>
                    </div>
                </div>
            </a>
            <div class="list-group list-group-flush">
                <a href="{% url 'students:dashboard' %}" class="list-group-item list-group-item-action bg-light">
                    <i class="fas fa-tachometer-alt"></i> Dashboard
                </a>
                <a href="{% url 'students:requirements' %}" class="list-group-item list-group-item-action bg-light">
                    <i class="fas fa-tasks"></i> Requirements
                </a>
                <a href="{% url 'students:list-of-document' %}" class="list-group-item list-group-item-action bg-light">
                    <i class="fa fa-paper-plane" aria-hidden="true"></i> Submitted Documents
                </a>
                <a href="{% url 'students:clockin' %}" class="list-group-item list-group-item-action bg-light">
                    <i class="fas fa-clock"></i> Clock In
                </a>
                <a href="{% url 'students:progress-report' %}" class="list-group-item list-group-item-action bg-light">
                    <i class="fas fa-chart-line"></i> Progress Report
                </a>
                <a data-toggle="modal" data-target="#logout" class="list-group-item list-group-item-action bg-light" style="cursor: pointer;">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
            </div>
        </div>
        <div class="modal fade" id="logout" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="loginModalLabel">Logout</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure do want to leave this page</p>
                    </div>
                    <div class="modal-footer">
                        <form>
                            <a href="javascript:void(0);" onclick="logout()" class="btn btn-primary">Logout</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="navbarDropdown"
                                role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-user mr-2"></i>{{ firstName }} {{ lastName }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'students:profile' %}">Profile</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'students:changePassword' %}">Change Password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" data-toggle="modal" data-target="#logout">Logout</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown mt-1">
                            <a class="nav-link d-flex align-items-center" href="#" id="notificationDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-bell mr-2"></i>
                                {% if unread_notifications_count > 0 %}
                                    <span class="badge badge-danger">{{ unread_notifications_count }}</span>
                                {% endif %}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="notificationDropdown">
                                <h6 class="dropdown-header">Notifications</h6>
                                {% if notifications %}
                                    {% for notification in notifications %}
                                        <form action="{% url 'students:mark_notification_as_read' notification.id %}" method="POST" style="display:inline;">
                                            {% csrf_token %}
                                            <button type="submit" class="dropdown-item" title="{{ notification.message }}">
                                                {{ notification.message }}
                                            </button>
                                        </form>
                                        <!-- Add a separator line -->
                                        <div class="dropdown-divider"></div> <!-- Bootstrap separator -->
                                    {% endfor %}
                                {% else %}
                                    <a class="dropdown-item" href="#">No new notifications</a>
                                {% endif %}
                            </div>
                        </li>         
                    </ul>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row mb-4">
                    <div class="col-lg-12">
                        <p class="mt-3 mb-2">Home / Changes Password</p>
                        <h4 class="mt-2 mb-3">Password</h4>
                        <form method="post" action="{% url 'students:changePassword' %}">
                            {% csrf_token %}
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-primary" role="alert">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <div class="form-group">
                                <label for="current_password">Current Password</label>
                                {{ form.current_password }}
                                {% if form.current_password.errors %}
                                    <div class="text-danger">
                                        {{ form.current_password.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="new_password">New Password</label>
                                {{ form.new_password }}
                                {% if form.new_password.errors %}
                                    <div class="text-danger">
                                        {{ form.new_password.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="confirm_password">Confirm Password</label>
                                {{ form.confirm_password }}
                                {% if form.confirm_password.errors %}
                                    <div class="text-danger">
                                        {{ form.confirm_password.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <button type="submit" class="btn btn-primary">Update Password</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        function logout() {
            localStorage.removeItem('is_student_logged_in');
            window.location.href = '{% url 'students:logout' %}';
        }
        document.addEventListener("DOMContentLoaded", function() {
            var imageInput = document.getElementById('id_Image');
            if (imageInput) {
                imageInput.classList.add('form-control', 'form-control-sm');
            }
        });
        
        $(".navbar-toggler").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

        $(document).ready(function() {
            // Function to update the preview box state
            function updatePreviewBox() {
                if ($('#current-image').length) {
                    $('#image-preview').addClass('with-image');
                } else {
                    $('#image-preview').removeClass('with-image');
                }
            }
            // Initial update on page load
            updatePreviewBox();
            // Handle file input change event
            $("input[type='file']").change(function(e) {
                let reader = new FileReader();
                reader.onload = function(e) {
                    $('#image-preview').html('<img src="' + e.target.result + '" style="max-width: 100%;" alt="New Image Preview" id="current-image">');
                    updatePreviewBox();
                }
                reader.readAsDataURL(this.files[0]);
            });
        });
    </script>
</body>
</html>

students/templates/students/custom_clearable_file_input.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main-dashboard.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <title>Admin - OJT Management System Dashboard</title>
</head>
<body>
    <input type="file" name="{{ widget.name }}" accept="image/*" {% include "django/forms/widgets/attrs.html" %}>
</body>
</html>