app/urls.py
from app import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('studentManagement', views.studentManagement, name='studentManagement'),
    path('register/', views.register, name='register'),
    path('profile', views.profile, name='profile'),
    path('logout', views.logoutView, name='logout'),
    path('content/', views.postContent, name='content'),
    path('student-logs/<int:id>/', views.studentInformation, name='student-logs'),
    # 
    path('changePass', views.changePass, name='changePass'),
    path('dashboard', views.mainDashboard, name='dashboard'),
    path('student-list', views.getAllListStudent, name='student-list'),
    path('student-submitted-list', views.getAllStudentSubmittedRequirements, name='student-submitted-list'),
    path('approve-student-list', views.getAllApproveStudents, name='approve-student-list'),
    path('pending-student-list', views.getAllPendingStudents, name='pending-student-list'),
    path('reject-student-list', views.getAllRejectStudents, name='reject-student-list'),
    path('computer-science-list', views.computerScienceStudents, name='computer-science-list'),
    path('information-technology-list', views.informationTechnologyStudents, name='information-technology-list'),
    path('editStudentDetails/<int:id>/', views.editStudentDetails, name='editStudentDetails'),
    # 
    path('approve_student/<int:id>/', views.approveStudent, name='approve_student'),
    path('reject_students/<int:id>/', views.rejectStudent, name='reject_students'),
    # 
    path('archivedStudent/<int:id>/', views.archivedStudent, name='archivedStudent'),
    path('get_admin_password_hash/', views.getAdminPasswordHash, name='get_admin_password_hash'),
    path('validate_admin_password/', views.validateAdminPassword, name='validate_admin_password'),
    
    path('unArchivedStudent/<int:id>/', views.unArchivedStudent, name='unArchivedStudent'),
    # 
    path('viewPendingApplication/<int:id>/', views.viewPendingApplication, name='viewPendingApplication'),
    path('view-student-details/<int:id>/', views.showStudentDetails, name='view-student-details'),
    path('setSchedule/<int:id>/', views.setSchedule, name='setSchedule'),
    # 
    path('announcement', views.postAnnouncement, name='announcement'),
    path('listOfAnnouncement', views.listOfAnnouncement, name='listOfAnnouncement'),
    path('all-content', views.listOfContent, name='all-content'),
    path('grading', views.getAllStudentsForGrading, name='grading'),
    path('submission', views.getTheSubmitRequirements, name='submission'),
    path('editAnnouncement/<int:id>/', views.editAnnouncement, name='editAnnouncement'),
    path('editContent/<int:id>/', views.editContent, name='editContent'),
    path('deleteAnnouncement/<int:id>/', views.deleteAnnouncement, name='deleteAnnouncement'),
    path('deleteContent/<int:id>/', views.deleteContent, name='deleteContent'),
    path('deleteRequirementDocuments/<int:id>/', views.deleteRequirementDocuments, name='deleteRequirementDocuments'),
    path('gradeCalculator/<int:id>/', views.gradeCalculator, name='gradeCalculator'),
    #
    path('set_rendering_hours/', views.set_rendering_hours, name='set_rendering_hours'),
    path('announcementNotLogin/', views.getAnnouncementNotLogin, name='announcementNotLogin'),
    path('announcementLogin/', views.getAnnouncement, name='announcementLogin'),
    path('return_to_revision/<int:id>/', views.return_to_revision, name='return_to_revision'),
    path('approve_document/<int:id>/', views.approve_document, name='approve_document'),
    path('update_document_score/<int:id>/', views.update_document_score, name='update_document_score'),
    path('view-requirements/<int:id>/', views.submittedRequirementOfStudents, name='view-requirements'),
    path('view-document/<int:id>/', views.submittedRequirementsOfStudents, name='view-document'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

homepage/urls.py
from homepage import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'homepage'

urlpatterns = [
    path('', views.webPage, name='main'),
    path('login-page', views.homePage, name='login-page'),
    path('students/login/', views.studentLogin, name='student_login'),
    path('coordinator/login/', views.coordinatorLogin, name='coordinator_login'),
    path('student-register', views.studentRegister, name='student-register'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/<str:token>/', views.reset_password, name='reset_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('students.urls')),
    path('admin/', admin.site.urls),
    path('coordinator/', include('app.urls')),
    path('secret-page/', include('superapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

students/urls.py
from students import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'students'

urlpatterns = [
    # path('', views.studentHome, name='home'),
    path('about/', views.aboutPage, name='about'),
    # path('login', views.studentLogin, name='login'),
    path('logout/', views.studentLogout, name='logout'),
    path('profile/', views.studentProfile, name='profile'),
    path('clockin/', views.ClockInAndOut, name='clockin'),
    path('about-page/', views.aboutLogin, name='about-page'),
    path('register/', views.studentRegister, name='register'),
    path('schedule/', views.scheduleSettings, name='schedule'),
    path('download/', views.exportTimeLogToPDF, name='download'),
    path('main-page/', views.welcomeDashboard, name='main-page'),
    path('requirements/', views.getTheRequirement, name='requirements'),
    path('delete_submission/<int:id>/', views.delete_submission, name='delete_submission'),
    path('log_lunch/', views.log_lunch, name='log_lunch'),
    path('dashboard/', views.mainPageForDashboard, name='dashboard'),
    path('announcement/', views.getAnnouncement, name='announcement'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/<str:token>/', views.reset_password, name='reset_password'),
    path('list-of-document/', views.getAllSubmittedDocuments, name='list-of-document'),
    path('announcement-page/', views.getAnnouncementNotLogin, name='announcement-page'),
    path('progress-report', views.typeTheDetailsProgressReportPdf, name='progress-report'),
    path('mark-notification-as-read/<int:id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

homepage/models.py
from django.db import models

# Create your models here.

homepage/templates/homepage/forgot_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <title>Forgot Password - OJT Management System</title>
    <style>
        .navbar-brand {
            display: flex;
            align-items: center;
        }
        .navbar-brand img {
            width: 50px;
            height: 50px;
            margin-right: 15px;
        }
        .navbar-brand p {
            margin: 0;
            margin-left: -10px;
            color: darkblue;
            font-size: 1.15rem;
        }
        .footer {
            background-color: #f8f9fa;
            padding: 20px 0;
            text-align: center;
        }
        .footer p {
            margin: 0;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'homepage:login-page' %}">
            <img src="{% static 'img/Logo.png' %}" alt="Logo" style="width:50px; height: 50px; margin-left: 15px;">
            <p>On The Job Management System</p>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <section class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Forgot Password</h5>
                        {% if messages %}
                            {% for message in messages %}
                                {% if message.tags == 'success' %}
                                    <div class="alert alert-success" role="alert">
                                        {{ message }}
                                    </div>
                                {% elif message.tags == 'error' %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ message }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        <form method="post" action="{% url 'homepage:forgot_password' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" name="email" required>
                            </div>
                            <button type="submit" class="btn btn-primary">Send Reset Link</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>    
    <!-- Footer -->
    <footer class="bg-light py-4 mt-4 fixed-bottom" id="footerMain">
        <div class="container">
          <div class="row justify-content-between align-items-center">
            <!-- Logo and description -->
            <div class="col-md-6 d-flex align-items-center">
              <a href="">
                <img src="{% static 'img/Logo.png' %}"
                     alt="ojt" class="img-fluid grayscale" width="80" height="80">
              </a>
              <div class="pl-3">
                <h5 class="mb-0">On The Job</h5>
                <small>Management System</small>
              </div>
            </div>
            <!-- Social media icon -->
            <div class="col-md-3 text-md-right text-center mt-3 mt-md-0">
              <a href="https://www.facebook.com/profile.php?id=100057567874785" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-facebook"
                     viewBox="0 0 24 24">
                  <path d="M9 8H6v4h3v12h5V12h4l1-4h-5V6c0-1 .334-1 1-1h3V0h-4c-3 0-4 1-4 4v4z"/>
                </svg>
                <span class="sr-only">Facebook page</span>
              </a>
            </div>
          </div>    
          <!-- Divider -->
          <hr class="my-4">
          <!-- Links and Copyright -->
          <div class="row align-items-center">
            <div class="col-md-6 d-flex flex-wrap justify-content-center justify-content-md-start mb-3 mb-md-0">
              <a href="" class="mr-3">Quality Policy</a>
            </div>
            <div class="col-md-6 text-center text-md-right">
              <span>Beta Version - &copy; 2024</span>
            </div>
          </div>
        </div>
    </footer>
    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        document.getElementById('currentYear').textContent = new Date().getFullYear();
    </script>
</body>
</html>

homepage/templates/homepage/home-page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate, max-age=0">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <title>OJT Management System - Login Page</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .btn-custom-navy {
            background-color: #000066;
            color: white;
        }
        
        .btn-custom-navy:hover {
            background-color: #000066;
            color: #fff;
        }
        .form-container {
            display: none;
            margin-top: 20px;
        }
        .form-container.active {
            display: block;
        }
        .navbar-brand {
            display: flex;
            align-items: center;
        }
        .navbar-brand img {
            width: 50px;
            height: 50px;
            margin-right: 15px;
        }
        .navbar-brand p {
            margin: 0;
            margin-left: -10px;
            color: darkblue;
            font-size: 1.15rem;
        }
        .outer-container {
            box-shadow: 0 8px 15px rgba(0, 0, 0, 0.2);
            padding: 20px;
            margin-top: 10px;
            border-radius: 6px;
        }
        #footerMain{
            box-shadow: 0 8px 15px rgba(0, 0, 0, 0.2);
        }     
        /* Style for the navbar */
        .navbar {
            transition: background-color 0.3s ease;
            z-index: 1000;
        }
        
        /* Default background color when at the top */
        .navbar-scroll {
            background-color: rgba(255, 255, 255, 0.8);
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .scrolled {
            background-color: rgba(0, 0, 0, 0.9);
        }
        body {
            padding-top: 70px;
        }
        @media (max-width: 900px) {
            .custom-hide-image {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div class="container mt-5 d-flex justify-content-center align-items-center">
        <div id="button-container" class="justify-content-center align-items-center text-center mt-4">
            <a class="navbar-brand d-flex align-items-center" href="{% url 'homepage:login-page' %}">
                <img src="{% static 'img/Logo.png' %}" 
                     alt="Logo" 
                     class="logo-img"
                     style="width: 50px; height: 50px;">
                <span style="margin-left: -7px; font-weight: 600; color: #6900ff;">On the Job Training Management System</span>
            </a>
            <h5 class="mb-4 mt-0 text-secondary" style="font-weight: 700;">College of Communication & <br> Information Technology</h5>
            <div class="d-flex flex-column align-items-center">
                <button class="btn btn-custom-navy btn-lg mb-3" style="padding: 8px; font-size: 1.5rem; width: 230px; font-weight: 600; border-radius: 26px;" onclick="showForm('coordinator')">Coordinator</button>
                <button class="btn btn-custom-navy btn-lg mb-3" style="padding: 8px; font-size: 1.5rem; width: 230px; font-weight: 600; border-radius: 26px;" onclick="showForm('student')">Student</button>
            </div>
        </div>                              
        <!-- Student Login Form -->
        <div id="student-form" class="form-container mt-0" style="width: 80%; max-width: 600px;">
            <div class="container d-flex justify-content-center align-items-center">
                <div class="justify-content-center align-items-center text-center mt-4">
                    <a class="navbar-brand d-flex align-items-center" href="{% url 'homepage:login-page' %}">
                        <img src="{% static 'img/Logo.png' %}" 
                             alt="Logo" 
                             class="logo-img"
                             style="width: 50px; height: 50px;">
                        <span style="margin-left: -7px; font-weight: 600; color: #6900ff;">On the Job Training Management System</span>
                    </a>
                    <h3 class="mb-3 mt-0 text-secondary" style="font-weight: 600;">Student Login</h3>
                </div>
            </div>
            <form id="student-login-form" action="/students/login/" method="POST" class="w-50 mx-auto">
                {% csrf_token %}
                <div id="student-error-message" class="alert alert-danger" style="display: none;"></div> <!-- Error message here -->          
                <div class="form-group">
                    <label for="student-username" class="text-secondary" style="font-weight: 500; font-size: 18px;">Username:</label>
                    <input type="text" class="form-control" id="student-username" name="Username" style="height: 45px; font-size: 18px;" placeholder="Enter your username....." required>
                </div>   
                <div class="form-group">
                    <label for="student-password" class="text-secondary" style="font-weight: 500; font-size: 18px;">Password:</label>
                    <input type="password" class="form-control" id="student-password" name="Password" style="height: 45px; font-size: 18px;" placeholder="Enter your password....." required>
                </div>           
                <div class="mb-2">
                    <a href="{% url 'homepage:forgot_password' %}">Forgot Password?</a>
                </div>        
                <div class="d-flex justify-content-between mt-2">
                    <button type="submit" class="btn btn-custom-navy" style="width: 110px; font-size: 19px; font-weight: 500;">Login</button>
                    <a type="click" onclick="goBack()" class="btn btn-custom-navy" style="width: 110px; font-size: 19px; font-weight: 500;">Back</a>
                </div>
                <div class="mt-3 text-center">
                    <a href="{% url 'homepage:student-register' %}" class="text-secondary" style="font-size: 14px; text-decoration: none; font-weight: 500;">Don’t have an account? Register now!</a>
                </div>                   
            </form>  
        </div>
        <!-- Coordinator Login Form -->
        <div id="coordinator-form" class="form-container mt-0" style="width: 80%; max-width: 600px;">
            <div class="container d-flex justify-content-center align-items-center">
                <div class="justify-content-center align-items-center text-center mt-4">
                    <a class="navbar-brand d-flex align-items-center" href="{% url 'homepage:login-page' %}">
                        <img src="{% static 'img/Logo.png' %}" 
                             alt="Logo" 
                             class="logo-img"
                             style="width: 50px; height: 50px;">
                        <span style="margin-left: -7px; font-weight: 600; color: #6900ff;">On the Job Training Management System</span>
                    </a>
                    <h3 class="mb-3 mt-0 text-secondary" style="font-weight: 600;">Coordinator Login</h3>
                </div>
            </div>
            <form id="coordinator-login-form" action="/coordinator/login/" method="POST" class="w-50 mx-auto mt-2">
                {% csrf_token %}
                <div id="coordinator-error-message" class="alert alert-danger" style="display: none;"></div> <!-- Error message here -->
                <div class="form-group">
                    <label for="coordinator-username" class="text-secondary" style="font-weight: 500; font-size: 18px;">Username:</label>
                    <input type="text" class="form-control" id="coordinator-username" name="username" style="height: 45px; font-size: 18px;" placeholder="Enter your username....." required>
                </div>
                <div class="form-group">
                    <label for="coordinator-password" class="text-secondary" style="font-weight: 500; font-size: 18px;">Password:</label>
                    <input type="password" class="form-control" id="coordinator-password" name="password" style="height: 45px; font-size: 18px;" placeholder="Enter your password....." required>
                </div>
                <div class="d-flex justify-content-between mt-2">
                    <button type="submit" class="btn btn-custom-navy" style="width: 110px; font-size: 19px; font-weight: 500;">Login</button>
                    <a type="click" onclick="goBack()" class="btn btn-custom-navy" style="width: 110px; font-size: 19px; font-weight: 500;">Back</a>
                </div>
            </form>
        </div>
    </div>
    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script>
        $(".navbar-toggler").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
        window.onload = function() {
            // Preventing back button navigation loop
            if (window.history.length > 1) {
                window.history.pushState(null, document.title, window.location.href);
                window.addEventListener('popstate', function(event) {
                    // Handle back button behavior appropriately
                    window.history.pushState(null, document.title, window.location.href);
                });
            }
        }
        function showForm(type) {
            document.getElementById('button-container').style.display = 'none';

            document.getElementById('student-form').classList.remove('active');
            document.getElementById('coordinator-form').classList.remove('active');
            {% comment %} document.getElementById('student-register-page').classList.remove('active'); {% endcomment %}
            if (type === 'student') {
                document.getElementById('student-form').classList.add('active');
            } else if (type === 'coordinator') {
                document.getElementById('coordinator-form').classList.add('active');
            }
        }
        function goBack() {
            document.getElementById('student-form').classList.remove('active');
            document.getElementById('coordinator-form').classList.remove('active');
            document.getElementById('button-container').style.display = 'block';
            // Clear error messages
            document.getElementById('student-error-message').style.display = 'none';
            document.getElementById('coordinator-error-message').style.display = 'none';
        }
        
        // Handling form submissions with AJAX
        document.getElementById('student-login-form').onsubmit = function(e) {
            e.preventDefault(); // Iwasan ang default na pag-submit ng form

            const formData = new FormData(this);
            fetch(this.action, {
                method: 'POST',
                body: formData
            }).then(response => response.json()).then(data => {
                if (data.error) {
                    document.getElementById('student-error-message').innerText = data.error;
                    document.getElementById('student-error-message').style.display = 'block'; // Ipakita ang error message
                } else if (data.redirect_url) {
                    window.location.href = data.redirect_url; // I-redirect ang user
                }
            }).catch(error => console.error('Error:', error));
        };

        document.getElementById('coordinator-login-form').onsubmit = function(e) {
            e.preventDefault(); // Iwasan ang default na pag-submit ng form

            const formData = new FormData(this);
            fetch(this.action, {
                method: 'POST',
                body: formData
            }).then(response => response.json()).then(data => {
                if (data.error) {
                    document.getElementById('coordinator-error-message').innerText = data.error;
                    document.getElementById('coordinator-error-message').style.display = 'block'; // Ipakita ang error message
                } else if (data.redirect_url) {
                    window.location.href = data.redirect_url; // I-redirect ang user
                }
            }).catch(error => console.error('Error:', error));
        };
    </script>
</body>
</html>